backend:
  name: git-gateway
  branch: main

media_folder: "static/media/uploads/"
collections:
  - name: "note"
    label: "Notes"
    folder: "content/notes/"
    create: true
    format: "toml-frontmatter"
    frontmatter_delimiter: "+++"
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "tags"
        label: "Tags"
        widget: "list"
      - name: "body"
        label: "Body"
        widget: "markdown"